### ISSUE TITLE
Cannot seem to install on MacOS

### ISSUE THREAD

**Issue by rebo** [koute/cargo-web#48] opened 2018-01-15 01:03 UTC
Hi on trying to run cargo install cargo-web  on macos I get the following error:

   Compiling app_dirs v1.1.1
error[E0619]: the type of this value must be known in this context
  --> /Users/rebo/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^

error: aborting due to previous error

Any ideas?

**Comment by koute** [comment] 2018-01-15 15:44
Hmm.... looks like an issue with the `app_dirs` crate. I don't have access to an OS X machine (and I haven't yet got to setting up OS X builds on Travis), but when I install the `x86_64-apple-darwin` target with `rustup` I can compile everything just fine (except the linking part, obviously.)

What exact OS X version are you running? On what exact Rust are you trying to compile it? Could you try to compile on `stable`, `beta` and the newest `nightly` Rust and report back?

**Comment by Elliot-Evans-95** [comment] 2018-01-16 20:36
I had the same issue but updating rust to the latest stable fixed this issue for me.
I think i was using an older rust version maybe 1.19

Working on:

Mac OS: 10.12.5
Rust: 1.23 Stable

**Comment by jordwest** [comment] 2018-01-18 00:03
Same issue here, but for me it failed on nightly `rustc 1.25.0-nightly (da569fa9d 2018-01-16)`.

These steps I believe fixed it:

```sh
rustup default stable
rustup update
```

Compiled for me on:
Mac OS 10.12.6
cargo 0.24.0
rustc 1.23.0

**Comment by koute** [comment] 2018-01-18 18:11
Yep. It looks like this is a regression in nightly Rust!

I've created a PR for the `app_dirs` crate to fix it: https://github.com/AndyBarron/app-dirs-rs/pull/29

**Comment by rebo** [comment] 2018-01-20 19:28
Hi thanks for looking at this everyone, to confirm that pull request fixes app-dirs.

**Comment by koute** [comment] 2018-02-03 00:48
Since it doesn't look like `app_dirs` crate will be fixed anytime soon I've forked it and pushed new `cargo-web` with a fix. So, closing!

**Closed by koute** 2018-02-03 00:48 UTC
