### ISSUE TITLE
Ensure error is actually visible if wasm fails to load

### ISSUE THREAD

**Issue by lukaslueg** [koute/cargo-web#147] opened 2018-10-20 21:35 UTC
https://github.com/koute/cargo-web/blob/8b9b5da0d767d8b9d8924bfedd16e54c5f0028e5/src/wasm_runtime_standalone.js#L46

This should be `error.toString()`, not just `error` to ensure that the error message is actually printed. If the object can't be cloned, the message will be `"<unavailable>"`, which is not helpful at all.

**Comment by lukaslueg** [comment] 2018-10-20 22:34
At least in the context of loading an extension, the error is always `<unavailable>`, unless it's manually turned into a string first.

**Comment by koute** [comment] 2018-12-03 21:55
> At least in the context of loading an extension, the error is always `<unavailable>`, unless it's manually turned into a string first.

That sounds to me like a bug of `console.log`. Are you sure it isn't a bug?

**Comment by Pauan** [comment] 2018-12-06 09:41
@koute Yeah, it's a bug with Firefox Extensions: using `console.log` with an `Error` works fine in Firefox, Chrome, and Chrome Extensions (just not in Firefox Extensions):

https://bugzilla.mozilla.org/show_bug.cgi?id=1327280
https://bugzilla.mozilla.org/show_bug.cgi?id=1462501
https://bugzilla.mozilla.org/show_bug.cgi?id=1393026

Technically it's an intentional feature omission (not a bug), but it sounds like they have plans to fix it regardless.

**Comment by lukaslueg** [comment] 2018-12-06 10:43
We could have the shim try to avoid the situation, yet as far as I'm concerned this can be closed.

**Comment by Pauan** [comment] 2018-12-06 11:01
@lukaslueg Personally, I think it's reasonable for the `web-extension` runtime to use `.toString()`, since this is an issue only with Firefox extensions. Other runtimes would be unchanged.

It would only affect [the wasm loading logic](https://github.com/koute/cargo-web/blob/6cb5ef63db4738c5800d733c3bdc901cabb437d2/src/wasm_runtime_web_extension.js#L21), other errors might still show up as `<unavailable>`. So the impact is minimized.

Do you want to make a PR for that, or should I?

**Comment by lukaslueg** [comment] 2018-12-06 12:51
Probably a one-line change, yet I wont get around doing it :-)

Am Do., 6. Dez. 2018 um 12:01 Uhr schrieb Pauan <notifications@github.com>:

**Comment by koute** [comment] 2018-12-06 16:05
Well, I'm fine with adding the `.toString()` if it's only in the context of the extension-specific runtime. We can always remove it later when the issue is fixed in Firefox.

**Comment by Pauan** [comment] 2018-12-06 18:05
This was fixed by https://github.com/koute/cargo-web/pull/162

**Comment by koute** [comment] 2018-12-12 21:03
Published as 0.6.22

**Closed by koute** 2018-12-12 21:04 UTC
