### ISSUE TITLE
Unable to install on Windows 7

### ISSUE THREAD

**Issue by vishalsodani** [koute/cargo-web#42] opened 2018-01-10 15:26 UTC
I have Windows7 64-bit. I fired this command `cargo install cargo-web`. I am using rustc 1.23.0.
I am getting an error -

`error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\
\Users\\VISHAL\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\VISH
AL\\AppData\\Local\\Temp\\cargo-install.VN2UTPu1F7E5\\release\\deps\\cargo_web-fdfc46013556d8f2.cargo_web0.rcgu.o......`

`= note: LINK : warning LNK4044: unrecognized option '/NATVIS:C:\Users\VISHAL\.rustup\toolchains\stable-x86_64-pc-windows-msvc
\lib\rustlib\etc\liballoc.natvis'; ignored
          LINK : warning LNK4044: unrecognized option '/NATVIS:C:\Users\VISHAL\.rustup\toolchains\stable-x86_64-pc-windows-msvc
\lib\rustlib\etc\libcore.natvis'; ignored
          LINK : fatal error LNK1181: cannot open input file 'synchronization.lib'
error: aborting due to previous error
error: failed to compile `cargo-web v0.5.2`, intermediate artifacts can be found at`

**Comment by koute** [comment] 2018-01-10 16:22
Can you `cargo install` other things? For example, `cargo install tokei` or `cargo install ripgrep`?

**Comment by vishalsodani** [comment] 2018-01-10 16:41
@koute I was able to install ripgrep and was also able to use it!

**Comment by koute** [comment] 2018-01-10 16:47
Hmm.... since you're using `x86_64-pc-windows-msvc` would it be possible for you to try to compile it with the `x86_64-pc-windows-gnu` target?

Also if you can then please paste the full compilation log.

**Comment by vishalsodani** [comment] 2018-01-10 17:38
@koute compilation for `x86_64-pc-windows-gnu` worked. 

Which log you wanted? the failed compilation?

**Comment by koute** [comment] 2018-01-10 17:39
> Which log you wanted? the failed compilation?

Yep! For some reason it doesn't build on the `msvc` target, so it would be useful to know *why*.

**Comment by coder543** [comment] 2018-01-13 01:14
I just built it with MSVC on my laptop, no problem. It's possible that the person who originally reported the issue is running an outdated version of Microsoft's toolchain, and there could be some compatibility issue there? I have Visual Studio 2017 installed, which provides the necessary linker for rust-msvc to use.

I wonder if @vishalsodani has an old version of Visual Studio, or what the issue could be.

**Comment by vishalsodani** [comment] 2018-01-13 01:24
@coder543 Yes I have VS 2012 installed.

**Comment by koute** [comment] 2018-01-23 20:08
Since it works on the `gnu` target and on a more recent MSVC - closing!

**Closed by koute** 2018-01-23 20:08 UTC
