### ISSUE TITLE
Provide hook with compile status for auto reload

### ISSUE THREAD

**Issue by MSleepyPanda** [koute/cargo-web#37] opened 2018-01-08 10:29 UTC
Auto reload would be handy for my kind of development.

Cargo-web could provide a websocket which pushes a notification when a newly compiled result is available. (Automagically injected?) Browser Side JS would listen and decide whether to reload or not. It would be enabled via a command line flag, e.g. `--recompile-status`.

**Comment by koute** [comment] 2018-01-08 19:54
I've added the `--auto-reload` argument to the `start` subcommand on `master`.

Unfortunately it doesn't use websockets as the websocket support in the library I currently use as a HTTP server doesn't really work for an usecase such as this. (From what I've tried it isn't possible to create a server which sends websocket messages to a passive client.)

**Comment by MSleepyPanda** [comment] 2018-01-09 00:07
Though the auto-reload itself worked, the server crashes badly afterwards. When launching with reload, it gets some poisoning according to what's available in the backtrace, when not it unwraps on `None`s. Short on time rn, might follow up with more details later on.

Anyways, thanks for looking after this so quickly!

**Comment by MSleepyPanda** [comment] 2018-01-09 00:07
Whoops misclicked

**Comment by koute** [comment] 2018-01-09 17:24
@MSleepyPanda Unfortunately I can't reproduce this problem, so I'd really appreciate if you could paste me a backtrace of the panic from `cargo-web` built in a `debug` mode. (And better yet - it would be great if you could point me to how to reproduce it.)

**Comment by koute** [comment] 2018-01-09 17:27
Ah, okay, I've managed to reproduce it. I'll fix it right away.

**Comment by koute** [comment] 2018-01-09 17:57
Should be fixed on `master`; let me know if it works for you now.

**Comment by koute** [comment] 2018-01-23 20:04
Just published a new version which has this added, so closing!

**Closed by koute** 2018-01-23 20:04 UTC
